### ISSUE TITLE
微社区接口升级 请将链接换为 discuz.hustca.com  

### ISSUE THREAD

**Issue by naihaishy** [HUST-CA/MyCA#3]
微社区接口升级 请将链接换为 discuz.hustca.com  或者http://wsq.discuz.com/?siteid=265482436
不建议使用http://wsq.discuz.com/?siteid=265482436 
discuz.hustca.com会自动识别手机版 转成微社区格式

**Comment by updateing** [comment]
Closed https://github.com/HUST-CA/MyCA/commit/dd4884b83c59112c44a9afb28749509a8467ede7
